import Navigation from "@/ui/segments/global/navigation";
import type { Metadata } from "next";

import { getTypefaceBySlug } from "@/api/typefaces";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Fuzar Collection",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { slug: string };
}) {
  try {
    const { slug } = await params;
    const typeface = await getTypefaceBySlug(slug);

    if (!typeface) {
      notFound();
    }

    return (
      <div className="relative w-full">
        <Navigation content={typeface} />
        {children}
      </div>
    );
  } catch (error) {
    console.error("Failed to fetch typeface:", error);

    return (
      <div className="relative w-full p-8 text-center">
        <h1 className="text-2xl font-bold text-red-600">
          Error Loading Typeface
        </h1>
        <p className="text-gray-600 mt-2">
          Failed to load typeface data. Please try again later.
        </p>
      </div>
    );
  }
}
