import { getAllTypefaces } from '@/api/typefaces';
import GlobalNavigation from '@/ui/segments/global/navigation/global-navigation';
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Fuzar Collection',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const allTypefaces = await getAllTypefaces();

  return (
    <html lang="en">
      <body>
        <GlobalNavigation allTypefaces={allTypefaces} />
        {children}
      </body>
    </html>
  );
}
